the error as been cleared in the file1  
th same error occurs again and again in this code 
